language: nix
nix: 2.2.2

cache:
  directories:
    - /nix/store

before_deploy:
  - rsync -avvL --inplace --no-whole-file result pages

deploy:
  local_dir: pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
