language: nix

env:
  - LC_ALL=en_US.UTF-8

notifications:
  email: false

before_deploy:
  - rsync -avvL --inplace --no-whole-file result/ pages

deploy:
  local_dir: pages
  provider: pages
  edge: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
