name: Publish presentations

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Install Nix
      uses: cachix/install-nix-action@v13
    - name: Build presentations
      run: |
        nix build
        rsync -rL --chmod=ugo=rwX --inplace --no-whole-file result/ gh-pages
    - name: Deploy to GitHub Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages

